swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
tags:
  - name: User Module
  - name: Transaction Module
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/getTranssaction:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions API
      description: API for fetching list of the month ask
      parameters:
        - in: query
          type: string
          name: Month
          description: search this month
          required: true
        - in: query
          type: string
          name: Year
          description: indicate the year of research
          required: true  
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: transactions month retrieved successully
          schema:
            $ref: '#/definitions/GetTransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transactionID}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary:  Transaction API
      description: API find transaction by ID
      operationId: getTransactionById
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionID
          in: path
          description: ID of transaction to be look
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses:
        '200':
          description: transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid TransactionID  
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: update a transaction to the database
      operationId: updateTransactionById
      parameters: 
        - in: header
          type: string 
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionID
          in: path
          description: ID of transaction update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: send transaction information
          required: true
          schema:
            $ref: '#/definitions/AddTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: transaction updating successully
          schema:
            $ref: '#/definitions/AddTransactionResponse'
        '400':
          description: Invalid TransactionID
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: delete a transaction to the database
      operationId: deleteTransactionById
      parameters: 
        - in: header
          type: string 
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionID
          in: path
          description: ID of transaction update
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses:
        '204':
          description: demande resource delete 
        '400':
          description: Invalid TransactionID
        '500':
          description: Internal Server Error
  /transactions/addTransaction:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: add a transaction to the database
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: send transaction information
          required: true
          schema:
            $ref: '#/definitions/AddTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: transaction add successully
          schema:
            $ref: '#/definitions/AddTransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  GetTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body: 
        type: object
        properties:
          id:
            type: string
          transactions:
            type: object
            description: data  
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body: 
        type: object
        properties:
          date:
            type: string
          description:
            type: string
          amont:
            type: string
          transaction type:
            type: string
          category:
            type: string
          notes:
            type: string
  AddTransaction:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amont:
        type: string
      transaction type:
        type: string
      category:
        type: string
      notes:
        type: string
  AddTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body: 
        type: object
        properties:
          id:
            type: string