swagger: "2.0"
info:
  description: "Possible API endpoints for phase two of Argent Bank project."
  version: "1.0.0"
  title: "Argent Bank API Documentation"
  termsOfService: "http://swagger.io/terms/"

host: "localhost:3001"
basePath: "/api/v2"
tags:
  - name: "User Transactions"
    description: "User's transactions data"
schemes:
  - "http"
paths:
  /user/profile/transactions/:
    get:
      tags:
        - "User Transactions"
      summary: "Transactions for the selected user account"
      description: "API to fetch user's transactions in one type of account"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
      responses:
        "200":
          description: "User transactions retrieved succesfully"
          schema:
            items:
              $ref: "#/definitions/Transactions"
        "400":
          description: "Invalid Fields"
        "404":
          description: "Not found"
        "500":
          description: "Internal server error"
    post:
      tags:
        - "User Transactions"
      summary: "Create a transaction"
      description: "Create a transaction"
      operationId: "postUserTransaction"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            $ref: "#/definitions/Transactions"
      responses:
        "200":
          description: "User transaction created succesfully"
        "400":
          description: "Invalid Fields"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server error"
  /user/profile/transactions/${transactionID}:
    get:
      tags:
        - "User Transactions"
      summary: "User selected transaction"
      description: "API to fetch user's selected transaction"
      operationId: "userTransaction"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
        - in: path
          name: transactionID
          type: integer
          required: true
          description: "ID of the transaction to get"
      responses:
        "200":
          description: "User transaction retrieved succesfully"
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: "Invalid Fields"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server error"
    put:
      tags:
        - "User Transactions"
      summary: "Update user selected transaction"
      description: "API to modify user's selected transaction"
      operationId: "updateSavings"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
        - in: "body"
          name: "body"
          description: "Transaction details that need to be updated"
          required: true
          schema:
            type: "object"
            properties:
              category:
                type: "string"
              notes:
                type: "string"
        - in: path
          name: transactionID
          type: integer
          required: true
          description: "Numeric ID of the transaction to get"
      responses:
        "200":
          description: Transaction details updated succesfully
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                format: "int32"
              message:
                type: "string"
              body:
                type: "object"
                properties:
                  category:
                    type: "string"
                  notes:
                    type: "string"

        "400":
          description: "Invalid Fields"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server error"
    delete:
      tags:
        - "User Transactions"
      summary: "Delete user selected transaction"
      description: "Delete user's selected transaction"
      operationId: "deleteUserTransaction"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
        - in: path
          name: transactionID
          type: integer
          required: true
          description: "ID of the transaction to get"
      responses:
        "200":
          description: "User transaction deleted succesfully"
        "400":
          description: "Invalid Fields"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server error"

definitions:
  Transactions:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      transaction:
        type: "object"
        properties:
          date:
            type: "string"
          description:
            type: "string"
          amount:
            type: "integer"
          type:
            type: "string"
          category:
            type: "string"
          notes:
            type: "string"
